# site settings
title: Lee Parham
subtitle: Portfolio
email: lee.p.parham@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Lee Parham
street_address: 1415 S. Taylor St.
city: Little Rock
state: AR
zip_code: 72204
country: United States of America
phone: (501) 563-8287

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/parhaml
linkedin_url: https://www.linkedin.com/in/parhaml


# build settings
markdown: kramdown

sass:
  style: compressed
